# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-dockerfile
build_from:
  aarch64: "ghcr.io/home-assistant/aarch64-base-python:3.10-alpine3.16"
  amd64: "ghcr.io/home-assistant/amd64-base-python:3.10-alpine3.16"
  armhf: "ghcr.io/home-assistant/armhf-base-python:3.10-alpine3.16"
  armv7: "ghcr.io/home-assistant/armv7-base-python:3.10-alpine3.16"
labels:
  org.opencontainers.image.title: "Viessmann Gridbox Connector (dev)"
  org.opencontainers.image.description: "Development of Viessmann Gridbox Connector"
  org.opencontainers.image.source: "https://github.com/unl0ck/homeassistant-addon-viessmann-gridbox"
  org.opencontainers.image.licenses: "Apache License 2.0"
args:
  TEMPIO_VERSION: "2021.09.0"
