# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-dockerfile
build_from:
  aarch64: "ghcr.io/home-assistant/aarch64-base-python:3.10-alpine3.16"
  amd64: "ghcr.io/home-assistant/amd64-base-python:3.10-alpine3.16"
  armhf: "ghcr.io/home-assistant/armhf-base-python:3.10-alpine3.16"
  armv7: "ghcr.io/home-assistant/armv7-base-python:3.10-alpine3.16"
args:
  TEMPIO_VERSION: "2021.09.0"
