# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: Viessmann Gridbox Connector add-on
version: "1.7.0"
slug: "gridbox_connector"
description: Fetch your live data from your Viessmann Gridbox
url: "https://github.com/unl0ck/homeassistant-addon-viessmann-gridbox/tree/main/GridboxConnectorAddon"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
init: false
map:
  - share:rw
discovery:
  - "mqtt"
services:
  - "mqtt:need"
options:
  username: "email"
  password: "password"
  wait_time: 60
schema:
  username: str
  password: password
  wait_time: int
  OverrideMqttUser: str?
  OverrideMqttPw: password?
  OverrideMqttServer: str?
  OverrideMqttPort: int?
image: ghcr.io/unl0ck/homeassistant-addon-viessmann-gridbox-{arch}
