name: Version Workflow

on:
    workflow_dispatch:
        inputs:
            version:
                description: 'Select the version type'
                required: true
                type: choice
                default: 'patch'
                options:
                    - major
                    - minor
                    - patch
                    - dev

jobs:
    build:
        runs-on: ubuntu-latest
        permissions:
          contents: write
          pull-requests: read
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Set up Python
              uses: actions/setup-python@v5
            
            - run: pip install bump-my-version

            - name: set Old Version 
              run: |
                echo "OLD_VERSIONE=$(bump-my-version show current_version)" >> $GITHUB_ENV
            
            - name: Bump Version
              run: bump-my-version bump ${{ github.event.inputs.version }}
            
            - name: set Current Version
              run: |
                echo "TAG_NAME=$(bump-my-version show current_version)" >> $GITHUB_ENV

            - name: Commit and Tag
              uses: stefanzweifel/git-auto-commit-action@v5
              with:
                tagging_message: ${{ env.TAG_NAME }}
                commit_message: "ci: ${{ env.OLD_VERSIONE }} -> ${{ env.TAG_NAME }}"

            - name: Build Changelog
              id: github_release
              uses: mikepenz/release-changelog-builder-action@v4
              env:
                GITHUB_TOKEN: ${{ github.token }}
            
            - name: Commit and Tag
              uses: stefanzweifel/git-auto-commit-action@v5
              with:
                tagging_message: ${{ env.TAG_NAME }}
                commit_message: "docs: ${{ env.OLD_VERSIONE }} -> ${{ env.TAG_NAME }}"
            
           