name: Release Stable

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Copy Release
        uses: ./copy_to_release.sh

      - name: Commit Stable
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "release: Release Stable Version"
